# baseball_scraper_config.yaml

project:
  name: BaseballScraper
  description: >
    A Python-based scraper that pulls MLB live scores from ESPN and saves the data in CSV and JSON formats.
    Automates execution using Windows Task Scheduler and PowerShell.
  version: 1.0.0
  author: Jeff Jones
  email: jcode3026@gmail.com
  github: ChefBoyRJeff
  date_created: 2025-05-20
  last_updated: 2025-05-20
  license: MIT
  repository: https://github.com/yourusername/BaseballProject

environment:
  language: Python
  python_version: "3.9+"
  virtual_env: venv
  dependencies:
    - requests
    - beautifulsoup4
    - pandas

structure:
  base_dir: BaseballScraper
  directories:
    - bots/python
    - data
    - venv
  files:
    - bots/python/scrape_scores.py
    - run_scraper.ps1
    - README.md

output:
  formats:
    - csv
    - json
  file_pattern: scores_YYYY-MM-DD.{csv,json}
  location: data/

scheduler:
  platform: Windows Task Scheduler
  method: PowerShell Script
  script_path: run_scraper.ps1
  task_example:
    program: powershell.exe
    arguments: -ExecutionPolicy Bypass -File "C:\\Path\\To\\run_scraper.ps1"
    frequency: daily
    time: "12:00 PM"

powerShellScript:
  filename: run_scraper.ps1
  contents: |
    cd "C:\Path\To\BaseballScraper"
    .\venv\Scripts\Activate.ps1
    python bots/python/scrape_scores.py

usage:
  setup:
    - Clone repository
    - Create virtual environment
    - Install dependencies
  run_manual:
    - Activate venv
    - Run scrape_scores.py
  run_scheduled:
    - Add task in Task Scheduler pointing to run_scraper.ps1
    - Confirm output in data/ folder

example_output:
  json: |
    [
      {
        "date": "2025-05-20",
        "home_team": "New York Yankees",
        "home_score": "5",
        "away_team": "Boston Red Sox",
        "away_score": "3",
        "status": "Final"
      }
    ]

contributing:
  guidelines:
    - Add scrapers for player stats, standings, schedules, injuries
    - Extend platform compatibility (Linux/macOS)
    - Add error logging and retry mechanisms

